### ISSUE TITLE
Problem for PhpMyAdmin and RippleAPI Code.

### ISSUE THREAD

**Issue by Nokeira** [Hazuki-san/ripple-auto-installer#3]
I need help guys, i don’t understand what it is saying this to me 
RippleAPI and the phpmyadmin programs doesn’t want to work for me, .....
The error message who appear says : " refused to connect. " for phpmyadmin
and the RippleAPI I don't understand those Lines:
> line 235 rm -rf /root/go/src/zxq.co/ripple
> line 236 mv /root/go/src/zxq.co/rippleapi /root/go/src/zxq.co/ripple

**Comment by Hazuki-san** [comment]
Have you try create another MySQL superuser?

**Comment by Nokeira** [comment]
Yes, but doesn't work too. :/

**Comment by Hazuki-san** [comment]
And you use that user right?

**Comment by Nokeira** [comment]
Yes, I do.

**Comment by Hazuki-san** [comment]
Make sure it's not "root" user.

**Comment by Nokeira** [comment]
Ok, I testing and I tell you.

**Comment by Hazuki-san** [comment]
Make sure to delete Ripple folder and /var/www/osu.ppy.sh/ folder before installing.

**Comment by Nokeira** [comment]
This is the error I get when I go on the service /phpmyadmin [https://cdn.discordapp.com/attachments/556664828517679113/567538336332251137/unknown.png](url)

**Comment by Hazuki-san** [comment]
Add me directly in Discord. I'll discuss about this later in Discord.
Discord: LoliZunhapan#9999
