### ISSUE TITLE
LETS not working??

### ISSUE THREAD

**Issue by LordDamionDevil** [Hazuki-san/ripple-auto-installer#6]
so everything works but LETS doesn't how does that happen?

 `
Traceback (most recent call last):
  File "lets.py", line 22, in <module>
    from handlers import apiCacheBeatmapHandler, rateHandler, changelogHandler
  File "/root/ripple/lets/handlers/rateHandler.py", line 54
    output = f"alreadyvoted\n{rating['rating']:.2f}"
SyntaxError: invalid syntax`

**Comment by ssCherry** [comment]
you use python3.6 lets.py for start LETS?

**Comment by LordDamionDevil** [comment]
I can't even use python3.6 as 16.04 comes with 3.5 even then I highly doubt it would matter as it is mad at the }

**Comment by ssCherry** [comment]
but i still think this error cause python version not 3.6 but i dont know right it or no.

**Comment by ssCherry** [comment]
And about avatars, you ran avatarserver?

**Comment by LordDamionDevil** [comment]
Yeah everything is running(except LETS cause of the issue) the avatars show up and etc just when it comes to uploading the browser just tells you this https://i.xn--urs05q.xyz/0paIaA.png

**Comment by ssCherry** [comment]
sorry i no idea to fix it

**Comment by LordDamionDevil** [comment]
Fixed it by adding proxy_request_buffering off; into nginx.conf in /etc/nginx but now the avatar uploading just says that it is not currently possible. as of the LETS issue I am still looking into it

**Comment by LordDamionDevil** [comment]
turns out it is due to the fact that i didn't use 3.6 I will prob make a pull request which fixes some of the issues
